### ISSUE TITLE
Kaspersky false positive?

### ISSUE THREAD

**Issue by montoner0** [joaomgcd/TaskerSettings#1]
I get this message today. The apk was installed from here. No issue with Market version.
![image](https://user-images.githubusercontent.com/13542804/118491908-20b15700-b728-11eb-8dc8-e7c23aa8afd0.png)

**Comment by joaomgcd** [comment]
This is a false positive that happens from time to time on some Antiviruses. I've contacted them about it. Last time I did they whitelisted the app so hopefully they'll do it again this time.  Thanks
