### ISSUE TITLE
Enabling WiFi does not work (Huawei P30 Lite)

### ISSUE THREAD

**Issue by psistorm** [joaomgcd/TaskerSettings#10]
Hi there,

I'm trying to toggle Flightmode and always enable Wifi. Flightmode is working so far, but I'm having troubles with WiFi. I installed the newest version of Tasker Settings 1.4.0 and did a very simple workflow just enabling Wifi.

When starting it ALWAYS asks for permissions to get position and then fails with the following output:

```
11.06.16/M lastWifiDisableAgoMS: 1649063176397
11.06.16/E check AP state
11.06.16/E AP state: 1
11.06.16/M lastWifiDisableAgoMS: 1649063176399
11.06.16/E current state: 1
11.06.16/E curval: 1
11.06.16/E Wi-Fi: cur: false new: true
11.06.16/E Wi-Fi: setWifiEnabled()
11.06.16/E add wait type Wifi Status Group time 2147483647
11.06.16/E add wait type Wifi Status Group done
11.06.16/M setKeepWifiOn: E/doWifiStatus1
11.06.16/E add wait task
11.06.21/E Fehler: null
11.06.21/E Couldn't toggle wifi: : java.util.concurrent.TimeoutException
```

Device is a Huawei P30 Lite (MAR-LX1A, Build 10.0.532 - EMUI 10.0.0, Android 10.0)
Tasker version is 5.15.14, Tasker Settings as mentioned above 1.4.0

**Comment by joaomgcd** [comment]
After installing this app you must grant it location permissions via Android Settings and NOT when the system prompts you. If you grant permissions when it asks you for them it'll simply crash and permissions won't be granted.
To manually grante the location permission open Andoird Settings > Apps > Tasker Settings and allow the permission there.

**Comment by psistorm** [comment]
Thanks that fixed the problem!
