### ISSUE TITLE
Version 1.4.0 crashes on the permissions screen for location

### ISSUE THREAD

**Issue by segevfiner** [joaomgcd/TaskerSettings#11]
Version 1.4.0 pops up a permission screen for location, but it crashes right after confirming it. This is on Android 10 running on OnePlus 5T. Guess you might need a logcat for this, will see if I can make one later.

**Comment by joaomgcd** [comment]
That's a known Android bug unfortunately. It was mentioned in the 1.3.0 release notes but I've added it to the 1.4.0 version too now :)

After installing this app you must grant it location permissions via Android Settings and NOT when the system prompts you. If you grant permissions when it asks you for them it'll simply crash and permissions won't be granted.
To manually grante the location permission open Andoird Settings > Apps > Tasker Settings and allow the permission there.

**Comment by segevfiner** [comment]
I wonder if you can get the app to popup a warning about this on startup?

**Comment by joaomgcd** [comment]
Hhmm, I could probably look into that. :) Thanks
