### ISSUE TITLE
Secure folder setting no longer working

### ISSUE THREAD

**Issue by sfarfalla** [joaomgcd/TaskerSettings#16]
Hi, was previously able to create a task:

Action:
Custom Setting:
Type: Secure
Name: hide_secure_folder_flag
Value: =:=toggle=:=

To change the status of the secure folder, or set it to 1 or 0. This doesn't seem to work anymore, there was another request raised here: https://www.reddit.com/r/tasker/comments/1026xat/feature_request_tasker_action_to_hide_secure/

Thanks!

**Comment by joaomgcd** [comment]
Hi. Tasker simply changes that setting, it doesn't actually do
anything with it. It's up to the system to interpret it. MAybe the system
changed and that setting is not valid anymore?

Thank you for your contact.

   *Join*
<https://play.google.com/store/apps/details?id=com.joaomgcd.join&referrer=utm_source%3Djoaoappssupport%26utm_medium%3Demail%26utm_campaign%3Dsignature%26anid%3Dadmob>:
connect multiple devices (send pushes, remote SMS, notifications) on
Android, Windows, Mac, Linux

<https://play.google.com/store/apps/details?id=com.joaomgcd.join&referrer=utm_source%3Djoaoappssupport%26utm_medium%3Demail%26utm_campaign%3Dsignature%26anid%3Dadmob>
*Tasker*
<https://play.google.com/store/apps/details?id=net.dinglisch.android.taskerm&referrer=utm_source%3Djoaoappssupport%26utm_medium%3Demail%26utm_campaign%3Dsignature%26anid%3Dadmob>:
customize/automate anything on your phone!

<https://play.google.com/store/apps/details?id=com.joaomgcd.join&referrer=utm_source%3Djoaoappssupport%26utm_medium%3Demail%26utm_campaign%3Dsignature%26anid%3Dadmob>
*AutoApps*
<https://play.google.com/store/apps/details?id=com.joaomgcd.autoappshub&referrer=utm_source%3Djoaoappssupport%26utm_medium%3Demail%26utm_campaign%3Dsignature%26anid%3Dadmob>:
add advanced functionality to Tasker via plugins

     <https://www.patreon.com/joaoapps>

João Dias

**Comment by joaomgcd** [comment]
There's nothing for me to fix, sorry. As I mentioned above, It's just how the system works.
