### ISSUE TITLE
Set mobile network on 3G upon connecting to a specific WIFI

### ISSUE THREAD

**Issue by mrBigKisses** [joaomgcd/TaskerSettings#18]
H Joao, 
I just tried to setup a profile that triggers a task upon connecting to a specific WIFI.
The task is **Setting the Mobile Network type to 3G**.

This would be perfect since I have a very bad 5G and 4G signal in a specific location where 3G signal is full. So I need to switch network type in order to have good voice connection (while DATA connection will be carried by the WIFI).

But when I try to Run the task it shows an **error:** "**unfortunately Google disabled the feature etc.**" 
I tried to install Tasker Settings (and i tested Wifi switching and it's working), but it seems that the issue is not addressed.

Do you have any hint?
KR,
R

**Comment by joaomgcd** [comment]
Yeah, this is a different issue that Tasker Settings cannot solve unfortunately, sorry!
