### ISSUE TITLE
WLAN nach update auf MIUI 14 geht nicht mehr

### ISSUE THREAD

**Issue by bahnuhr** [joaomgcd/TaskerSettings#19]
Handy: Xiaomi Mi 11
Gestern update auf miui 14 gemacht.

Nun funktioniert wlan Umschaltung per tasker nicht mehr.
Probiert habe ich schon:
tasker settings 1.4.0 und 1.5.0 sowie tasker permission.
Es kommt weiterhin die Abfrage ob das wlan umschalten erlaubt werden soll.
Ich habe bisher keine Lösung gefunden.
Hat jemand dafür schon eine Lösung/workflow ?

-------------------------------------------
or english:
Mobile: Xiaomi Mi 11
Updated to miui 14 yesterday.

Now wlan switching via tasker no longer works.
I have already tried:
tasker settings 1.4.0 and 1.5.0 and tasker permission.
There is still the query whether the wireless switch should be allowed.
I haven't found a solution yet.
Does anyone have a solution/workflow for this?

**Comment by joaomgcd** [comment]
Hi, check here: https://github.com/joaomgcd/TaskerSettings/pull/13
