### ISSUE TITLE
Android asking to give location permission every time power changed

### ISSUE THREAD

**Issue by Thetechguru-net** [joaomgcd/TaskerSettings#2]
Whenever power is connected or disconnected from phone, Android is popping up error that Tasker Settings was updated and needs location permission now.   S teen shot attached. 
![Screenshot_20210629-153925_Permission controller](https://user-images.githubusercontent.com/74467314/123858006-048d0200-d8f1-11eb-9645-ff2aac603d1f.jpg)

**Comment by Thetechguru-net** [comment]
Probably should have mentioned.  Samsung Galaxy S10, Android 11.

**Comment by joaomgcd** [comment]
Check out the release notes for the [latest version](https://github.com/joaomgcd/TaskerSettings/releases/tag/v1.3.0) :) Seems to be an Android bug. You need to go into Android Settings and allow the location permission manually.

**Comment by Thetechguru-net** [comment]
I did give it location always permission and it still occurred.

**Comment by joaomgcd** [comment]
Are you sure you gave it to **Tasker Settings** and not Tasker itself?

**Comment by Thetechguru-net** [comment]
I'll try again and retest.

**Comment by joaomgcd** [comment]
Thanks

**Comment by Thetechguru-net** [comment]
Well, that is just weird.  Re-installed (I had downgraded) and it didn't ask for permission when I applied power.  I added the permission manually anyway, but all seems good now.  I did do a full reinstall of Tasker yesterday so maybe there was some glitchy interaction that fixed it.

**Comment by joaomgcd** [comment]
Great, glad it works! :)
