### ISSUE TITLE
Can't toggle WiFi after recent updates

### ISSUE THREAD

**Issue by montoner0** [joaomgcd/TaskerSettings#23]
WiFi doesn't toggle anymore after some of the recent Tasker updates. I tried to update Tasker Settings to 1.5 and 1.6 (both Xiaomi and non-Xiaomi versions) but it didn't help. All permissions and other recommendation are configured.

Tasker version is 6.1.32
Android 11
MIUI 12.5.7

**Comment by joaomgcd** [comment]
What happens when you try? Do you get an error?

**Comment by joaomgcd** [comment]
Seems like MIUI is blocking it then :/ Sorry, I don't think I can help.

**Comment by montoner0** [comment]
Err. But it worked previously! It all started after some recent Tasker update and worked before quite normal.

**Comment by montoner0** [comment]
I figured it out myself. It was somehow related to (I think) an airplane mode. I admit, I forgot to mention that the phone was in the airplane mode
I've installed a logcat viewer and found there an error `setWifiEnabled doesn't work in airplane mode` (it would be nice if Tasker show this instead of success). Then I tried to play with `airplane_mode_radios` option and after a reboot WiFi started to toggle again (not sure if the option helped but still).
> Please understand that Tasker is using a hack to do this, so it may not be supported on all devices.

I perfectly understand this but since the feature worked previously and therefore _is_ supported by the device I'd expected some more help.

**Comment by joaomgcd** [comment]
Oh, I see! Yeah, I should've thought of that, sorry! Other users already mentioned the same but I forgot.

Unfortunately there's no way for Tasker to detect that error though, as far as I'm aware. Tasker calls the Android API and it doesn't report an error back to Tasker, so Tasker also doesn't report an error to the user.

I'm glad you found the solution! Again, sorry for not being more helpful in the first place.

**Comment by montoner0** [comment]
It has stopped to work again and I can't fix it back... This is super frustrating...
