### ISSUE TITLE
Tasker Setting app fails to install on Android 14 Beta 3

### ISSUE THREAD

**Issue by tilaksidduram** [joaomgcd/TaskerSettings#24]
The latest version 1.6.0 of the Tasker Settings app is not getting installed on Android 14 Beta 3. It errors out saying "App not Installed as app isn't compatible with your Phone. I am trying to install the app on a Pixel 7 pro.

![image](https://github.com/joaomgcd/TaskerSettings/assets/4350786/7d63e135-7080-4966-a35d-7ed01f424954)

**Comment by joaomgcd** [comment]
Unfortunately with Android 14 you have to install the APP via ADB:

**adb install --bypass-low-target-sdk-block FILENAME.apk**

Sorry for the trouble!

**Comment by tilaksidduram** [comment]
Thanks @joaomgcd for your response. I was able to install the app via ADB and now I'm able to toggle BT using tasker.

**Comment by joaomgcd** [comment]
👍

**Comment by abdullahO2** [comment]
@joaomgcd 
Please, is it possible to do the command "adb install --bypass-low-target-sdk-block 1.apk" through the phone?
I tried LADB through "Wireless ADB Debugging" and I tried "Shamiko + ashill" and I tried:
pm install --bypass-low-target-sdk-block /mnt/sdcard/1.apk
pm install --bypass-low-target-sdk-block /storage/emulated/0/1.apk
This didn't work for me

**Comment by joaomgcd** [comment]
Unfortunately, as far as I know, you really need to do it via PC, sorry!
