### ISSUE TITLE
Virus scanning reports 

### ISSUE THREAD

**Issue by nicoleahmed** [joaomgcd/TaskerSettings#25]
Positive virus results for tasker settings 1.6 (downloaded from github joaomgcd repository)

I've seen the closed kaspersky issue  from a few years ago. 

Why is this getting labelled as malicious? 

![Screenshot_20230809-014655](https://github.com/joaomgcd/TaskerSettings/assets/38244338/e5f396b4-4aeb-40a5-af94-07d8cc5c7ae9)
![Screenshot_20230809-015118](https://github.com/joaomgcd/TaskerSettings/assets/38244338/9ce998b9-a483-4dd1-bb1e-3a55d4174f89)
![Screenshot_20230809-015123](https://github.com/joaomgcd/TaskerSettings/assets/38244338/ca0069de-ec74-4c3b-a3c2-87858f82de37)
![Screenshot_20230809-014526](https://github.com/joaomgcd/TaskerSettings/assets/38244338/386afe43-3302-4980-acf2-9385287c5937)

**Comment by joaomgcd** [comment]
Hi. Sorry, but I don't know why it's being labeled that way, since I don't control what virus scanners label as malicious... The app is open source so you can see that it's not doing anything wrong...
