### ISSUE TITLE
Allow Tasker Settings to turn on Wi-FI?

### ISSUE THREAD

**Issue by Takumiboo** [joaomgcd/TaskerSettings#27]
I'm using a SONY Xperia 1V running Android 13.
I installed Tasker Settings apk, but when turning on Wi-Fi with Tasker, Android prompted me like below.
[https://www.reddit.com/r/tasker/comments/13539gl/have_to_click_allow_to_enable_wifi_with_tasker/](https://www.reddit.com/r/tasker/comments/13539gl/have_to_click_allow_to_enable_wifi_with_tasker/)

When I turn off Wi-Fi with Tasker, Android doesn't prompt me.

Is there any workaround?

**Comment by joaomgcd** [comment]
Hi. That's a setting somewhere in your device's system settings that you have to change. Tasker itself doesn't show that popup. 
If you can find the system setting that disables that popup, it should work correctly! :)

Hope this helps!
