### ISSUE TITLE
Kaspersky False Positive

### ISSUE THREAD

**Issue by skyhigh24** [joaomgcd/TaskerSettings#28]
Once Again, An Antivirus Program deletes the TaskerSettings1.6.apk File due to Trojan.AndroidOS.Boogr.gsh...
(Happens on both: the Normal and the Xiaomi/Huawai one) 
Tried to report a False Positive at Kaspersky but i cant because the Button is not showing for me. (or their Documentation is too old and they removed the Report Function)

Tested it on VirusTotal, theres some others, too:
Normal:
https://www.virustotal.com/gui/file/4ad77033d947dd036bb4457bf56f7710f73a2b24fb984bed45f9157c237d6aea
Xiaomi/Huawai:
https://www.virustotal.com/gui/file/7033feb93a3c26941b3ebf32223df511fad08d9a6a0289e327fd4c24e9450679

Can someone try to report the False Positive or is this a NeverEnding Story?

**Comment by joaomgcd** [comment]
Yeah, I don't know what it could be, sorry :( Something in the code must be triggering this.

**Comment by ruifung** [comment]
And on my side, windows defender just flagged this as 'Trojan:AndroidOS/Multiverze'

**Comment by sp4rkie** [comment]
then throw the windows-defender in the garbage 😀

**Comment by skyhigh24** [comment]
@sp4rkie i want to see, how you throw the Defender (an OS integrated Antivirus solution) in the garbage 🤔

@joaomgcd in Forums the question "is tasker settings Safe to Install" repeats every now and then. 
I know theres nothing you can do about the false flagging of the Files, how about an Info in the readme of this repo?

**Comment by yurividal** [comment]
Windows defender and Brave Browser both flagged v1.6 as Trojan.

<img width="375" alt="image" src="https://github.com/joaomgcd/TaskerSettings/assets/8555749/f0df94ee-5acc-4e1e-bbdf-b7a4d86b03f0">

**Comment by joaomgcd** [comment]
@skyhigh24 thanks, I've now added a note in the Readme.
