### ISSUE TITLE
No installation via ADB possible

### ISSUE THREAD

**Issue by VJuric** [joaomgcd/TaskerSettings#29]
I'm using Pixel 8 Pro and after installing Tasker I tried installing the TaskerSettings via ADB.

Error:
C:\platform-tools>adb install --bypass-low-target-sdk-block Tasker.Settings.1.6.0.apk
Performing Streamed Install
adb: failed to install Tasker.Settings.1.6.0.apk: Failure [INSTALL_FAILED_VERIFICATION_FAILURE: Install not allowed for file:///data/app/vmdl1663756578.tmp]

Please support me here.

**Comment by joaomgcd** [comment]
Hi. Do you have developer options enabled on your device? Not sure if that's the issue though, but it's worth a try.

**Comment by VJuric** [comment]
Sure 😀

**Comment by joaomgcd** [comment]
Thanks for letting me know! I'll update the instructions. :)

**Comment by chrisonline** [comment]
Did not work (anymore?!) on Pixel 8 and Android 14.

Have disabled in DEV options "Check apps installed via USB", but if I try to install via ADB:
`adb install .\Tasker.Settings.1.6.0.apk`

I get this error:
```
Performing Streamed Install
adb: failed to install .\Tasker.Settings.1.6.0.apk: Failure [INSTALL_FAILED_DEPRECATED_SDK_VERSION: App package must target at least SDK version 23, but found 21]
```

**Comment by chrisonline** [comment]
Found a solution to this. You need to install it with this flag added:
`adb install --bypass-low-target-sdk-block .\Tasker.Settings.1.6.0.apk`

**Comment by joaomgcd** [comment]
Yep, that's mentioned here: https://github.com/joaomgcd/TaskerSettings

Glad you got it.

**Comment by chrisonline** [comment]
Oh sorry didn't not read the main page and was going straight to the issues ;-)

**Comment by joaomgcd** [comment]
👍
