### ISSUE TITLE
Not able to install

### ISSUE THREAD

**Issue by theLittlePrinceAD** [joaomgcd/TaskerSettings#3]
Dear Developer, trying to install TaskerSettings (both v.1.2 & v.1.3) I get a screen like attached, where pressing NEXT does not do anything and installation gets stuck. The same is if I first uninstall v.1.0.3 and try to install just the new version. Having Oreo 8.0 (HP Sony XZ2 compact)
Any ideas how to solve it?

![TaskerSettings installation](https://user-images.githubusercontent.com/44745082/126265925-cc5af4ac-3d48-4ce3-8515-dc3c58f431f1.png)

**Comment by joaomgcd** [comment]
Does it help if you uninstall it first?

**Comment by theLittlePrinceAD** [comment]
Unfortunately uninstalling the old version first does not change the screen I am coming to (attached pic in first message). I have tried to find some installer which is not using the android package installer hoping to give me a way to react, but could not find ☹

**Comment by kripindef** [comment]
I have same problem. It says "app is not installed"

**Comment by joaomgcd** [comment]
Sorry, seems like a bug in the installer :( I don't think I can help.
