### ISSUE TITLE
App is not compatible with phone (presumably Android 14)

### ISSUE THREAD

**Issue by brake16** [joaomgcd/TaskerSettings#30]
Pixel 8 Pro.  I downloaded the Tasker Settings app on the phone and tried to install (yes, install permissions were granted first).  The error I received was "App not installed as app isn't compatible with your phone."

**Comment by joaomgcd** [comment]
Check [here](https://github.com/joaomgcd/TaskerSettings/issues/29).

**Comment by brake16** [comment]
I got it working.  Thanks João!
