### ISSUE TITLE
java.lang.IllegalArgumentException: Size must be positive

### ISSUE THREAD

**Issue by ATimesThree** [joaomgcd/TaskerSettings#31]
Trying to install using adb gives the following error:
![image](https://github.com/joaomgcd/TaskerSettings/assets/40924386/eabfb0c7-ec06-4f5a-a145-e1fc66bd691b)

Device is showing up:
![image](https://github.com/joaomgcd/TaskerSettings/assets/40924386/22f22a75-f124-4cb4-8293-80432a5d4978)

Settings:
- Developer mode on
- Developer options on
- USB debugging on
- Tried setting USB settings to both "File transfer" and "No data transfer"

Phone: Pixel 8 Pro
OS: Android 14

**Comment by ATimesThree** [comment]
I just tried installing the 1.4 version and it worked successfully, however the 1.6 does not work for some reason..

**Comment by joaomgcd** [comment]
Maybe the download didn't finish correctly? Check if the file is there and has the correct size.

**Comment by ATimesThree** [comment]
That seemed to be the problem :) Windows Defender flagged it as a Trojan and stopped it from downloading completely.

**Comment by joaomgcd** [comment]
Glad you found the issue!
