### ISSUE TITLE
Toggle Bluetooth on MIUI won't work (Tasker 6.2.22, TS 1.6+)

### ISSUE THREAD

**Issue by happybear88** [joaomgcd/TaskerSettings#35]
### OS and app info
Tasker: 6.2.22
Tasker Settings: 1.6.0, 1.7.1, 1.7.1 Huawei.Xiaomi
Android 13 TKQ1
MIUI Global 14.0.6
[TaskerBT.zip](https://github.com/joaomgcd/TaskerSettings/files/13901670/TaskerBT.zip) contains full text of errors, and screenshots of app versions, tasks, permission settings 

### Issue description
Unable to automatically turn BT on or off with Tasker Settings.

-  **Tasker Settings 1.7.11.7.1 Huawei.Xiaomi**  throws an exception despite having a permission to change BT connectivity (see [TaskerBT.zip](https://github.com/joaomgcd/TaskerSettings/files/13901670/TaskerBT.zip) for the full error)
` Couldn't toggle bluetooth: : java.lang.SecurityException: Need android.permission.BLUETOOTH_CONNECT permission for android.content.AttributionSource
`
-**Tasker Settings 1.6.0 and 1.7.1** has no available permission to change BT connectivity. I'm prompted to allow BT on or off every time the task runs. 

### Notes
- I have followed https://github.com/joaomgcd/TaskerSettings and set all permissions via the Android settings
- The behavior is the same for turning BT on and off.
- My scenarios are to turn on Bluetooth when the phone is locked, e.g. DND turns off on schedule, or I have missed calls from starred contacts, etc

I'll appreciate any suggestions.
Thanks!

**Comment by joaomgcd** [comment]
> I'm prompted to allow BT on or off every time the task runs.

That's usually a setting somewhere in your device's system settings that you have to change. Tasker itself doesn't show that popup. 
If you can find the system setting that disables that popup, it should work correctly! :)

Hope this helps!

**Comment by happybear88** [comment]
Thanks @joaomgcd , but why are you closing as completed already? There are two problems I'm raising here.

1/ The standard version throws an exception. Why is this not a problem from your perspective?

2/ The Xiaomi version is not working as I expect (my expectations could be wrong, but that's not the end of the story for me). 

Here's the Xiaomi version of the app with the BT management setting
![image](https://github.com/joaomgcd/TaskerSettings/assets/18210408/eda8c3b7-27f7-4845-9e6c-12d294d64ee5)

From the releases
_On some Huawei devices you'll need to use the special Huawei/Xiaomi APK below so that when you try to toggle WIFI it won't always ask you for permission to toggle it. More info here: https://github.com/joaomgcd/TaskerSettings/pull/13_

I'm having a similar issue with Bluetooth, at least the symptom is the same - I'm always prompted for permission. If this version is not able to manage BT the same way it manages Wi-FI, can we convert the issue to the Feature Request for BT?

Thanks!

**Comment by happybear88** [comment]
I have clarified the issue description and the comment above, please review again. I've also updated 
[TaskerBT.zip](https://github.com/joaomgcd/TaskerSettings/files/13901670/TaskerBT.zip) with the originally missing exception info.

**Comment by joaomgcd** [comment]
Sorry, I closed it because usually the solution I presented fixes the situation and sometimes people forget to reply that it works so I started closing the issue preemptively because I would then forget to close it later if people didn't reply 😅

Ok, let's see.

1. Can you please try disabling/re-enabling the Bluetooth/Nearby Devices permission for both Tasker and Tasker Settings and see if that helps?
2. The special release Huawei/Xiaomi release was made because it was found that targeting a higher API level would make the Wifi prompt not show up on some devices. It's not related to the Bluetooth prompt unfortunately. If you're saying that the bluetooth prompt is still appearing and that it can't be disabled in system settings then we'll need to find a different workaround somehow. I'm just not sure what it is...

Hope this helps!

**Comment by Tyri0n** [comment]
toggling nearby devices permission worked for me (a random lurker), thanks.

>     1. Can you please try disabling/re-enabling the Bluetooth/Nearby Devices permission for both Tasker and Tasker Settings and see if that helps?

**Comment by Gundi17** [comment]
For me disabling/re-enabling the Bluetooth/Nearby Devices permission for both Tasker and Tasker Settings unfortunately did not work. I tried repeatedly, also in combination with a restart. This problem only started today, and I am not sure what caused it as I did not change anything. I'm on a Xiaomi 11 Lite 5G NE with MIUI 14.0.8.

**Comment by happybear88** [comment]
@joaomgcd thanks a lot for your suggestions. The problem with 1.7.1 Huawei.Xiaomi indeed went away after toggling back and forth the Bluetooth and Nearby Devices permissions for both Tasker and Tasker Settings. This survived a reboot as well.

FWIW, I didn't have Tasker Settings installed until today. But Tasker got updated to 6.2.22 and stopped disabling BT for me. So I went ahead with Tasker Settings install and ran into this issue.

**Comment by joaomgcd** [comment]
Yeah, it's a new issue because I had to update Tasker's target API to 33 which made the app not be able to toggle BT. Glad it's fixed! :) Thanks!

**Comment by honggiwei** [comment]
I have tried install 'tasker setting', but it still appear user prompt which is annoying.
I try 3'party code. Bt toggle app.
It work and no user prompt appear.
So, I think 'tasker setting' miss something.

https://github.com/brendanbeavis/Android_BluetoothToggle

**Comment by joaomgcd** [comment]
Hi. Can you try disabling and re-enabling the Bluetooth and Nearby Devices permission for both Tasker and Tasker Settings? Thanks in advance!

**Comment by honggiwei** [comment]
I know the method you mentioned. I have read your previous articles. Of
course, I have also tried it, but it still didn't work, so I looked for
alternative software solutions。

Thanks。
