### ISSUE TITLE
Can this be used to automatically connect to drone Wi-Fi or action cam Wi-Fi?

### ISSUE THREAD

**Issue by Bboy486** [joaomgcd/TaskerSettings#4]
I have my main Wi-Fi in my house so I can see the use case using this with Tasker. However what I really would like to do is if a Wi-Fi from my action cams or drone or other Wi-Fi device turns on the task can automatically detect that and switch over asking me if I want to connect to that specific Network or stay in my existing one.

**Comment by joaomgcd** [comment]
Hi! Yes! :) Use the *Connect To Wifi* action and it should work!

Thank you for your contact.

   *Join*
<https://play.google.com/store/apps/details?id=com.joaomgcd.join&referrer=utm_source%3Djoaoappssupport%26utm_medium%3Demail%26utm_campaign%3Dsignature%26anid%3Dadmob>:
connect multiple devices (send pushes, remote SMS, notifications) on
Android, Windows, Mac, Linux

<https://play.google.com/store/apps/details?id=com.joaomgcd.join&referrer=utm_source%3Djoaoappssupport%26utm_medium%3Demail%26utm_campaign%3Dsignature%26anid%3Dadmob>
*Tasker*
<https://play.google.com/store/apps/details?id=net.dinglisch.android.taskerm&referrer=utm_source%3Djoaoappssupport%26utm_medium%3Demail%26utm_campaign%3Dsignature%26anid%3Dadmob>:
customize/automate anything on your phone!

<https://play.google.com/store/apps/details?id=com.joaomgcd.join&referrer=utm_source%3Djoaoappssupport%26utm_medium%3Demail%26utm_campaign%3Dsignature%26anid%3Dadmob>
*AutoApps*
<https://play.google.com/store/apps/details?id=com.joaomgcd.autoappshub&referrer=utm_source%3Djoaoappssupport%26utm_medium%3Demail%26utm_campaign%3Dsignature%26anid%3Dadmob>:
add advanced functionality to Tasker via plugins

     <https://www.patreon.com/joaoapps>

João Dias
