### ISSUE TITLE
TaskerSettings saying compatibility issues with Tasker 

### ISSUE THREAD

**Issue by Nitesh-13** [joaomgcd/TaskerSettings#40]
Version: Tasker v6.2.22
Tasker Settings v1.7.0

Tried to install TaskerSettings via adb after installing Tasker and came across the following error
```
adb: failed to install TaskerSettings.apk: Failure [INSTALL_FAILED_DUPLICATE_PERMISSION: Package com.joaomgcd.taskersettings attempting to redeclare permission com.joaomgcd.taskersettings.SET_SETTING already owned by net.dinglisch.android.taskerm]
```

**Comment by joaomgcd** [comment]
Did you install Tasker from Google Play and Tasker Settings from the version on this github?

**Comment by Nitesh-13** [comment]
Yes I did install Tasker from Google Play Store. I downloaded tasker settings from this repository.

**Comment by killua99** [comment]
same issue on my Samsung S22 ultra, I uninstall the app and tried to install it back without success

**Comment by joaomgcd** [comment]
hhmm, what if you uninstall Tasker and then install Tasker Settings first? Does that work?

**Comment by killua99** [comment]
So I tried what you mention.

I uninstall tasker, rebooted the phone, clear most of the cache files ... still mention that is not compatible with my device

A Samsung Ultra 20 with latest update.

**Comment by Orbitron-HD** [comment]
I have this same issue with Tasker Settings v1.2.0. I can't seem to find any solution anywhere.

**Comment by joaomgcd** [comment]
Hi. Please check the note about Android 14 here: https://github.com/joaomgcd/TaskerSettings/

Sorry for the inconvenience!
