### ISSUE TITLE
TaskerSetting 1.7.1 fails changing mobile network type on Android 14 and OnePlus OxygenOS 14

### ISSUE THREAD

**Issue by Peter-1130** [joaomgcd/TaskerSettings#44]
After upgrading my OnePlus 9 Pro to Android 14 I also upgraded TaskerSettings to 1.7.1 via PC and ADB-command. Recived confirmation, so far OK. Toggeling WiFi or Bluetooth (both on/off) without problems, but failing on change of mobile network types with the usual error-message about the targt_api.

Not sure, if this depends on OxygenOS 14 or if this is a common error on other devices too.

Any suggestion or advice is much appreciated.

Greetings

Peter

**Comment by Peter-1130** [comment]
Thanks for your reply.

ADB Wifi is started succesfully when booting with the help of LADB (adb tcpip 5555) and Taskes`s CheckADBWifi() function reports true.

Regards

Peter

**Comment by joaomgcd** [comment]
Can you please show me the exact message you get when you run the Mobile Network action? Thanks!

**Comment by Peter-1130** [comment]
Sure, please see attchment of the function and the error code:

[tsk.pdf](https://github.com/joaomgcd/TaskerSettings/files/14494062/tsk.pdf)

**Comment by joaomgcd** [comment]
Oh, I thought you were talking about the **Mobile Data** action, sorry about that. Unfortunately that action can't be brought back, sorry! :(
