### ISSUE TITLE
Compatibility with WearOS for Bluetooth Toggle

### ISSUE THREAD

**Issue by HoreaM** [joaomgcd/TaskerSettings#45]
Hi, firstly I wanted to thank you for developing these wonderful apps, I can't ever imagine going back to using my Android phone without Tasker on it.
I was working on adding some automations for my Galaxy Watch 5 using AutoWear and realized that whatever I was doing, I couldn't get the Bluetooth to toggle on/off.
I tried the AutoWear Setting for enabling/disabling Bluetooth, tried setting the 
`bluetooth_on=0`
Secure Setting, even tried with the Airplane Mode setting and also setting the 
`airplane_mode_on=1`
while having 
`airplane_mode_radios=cell,bluetooth,wifi,nfc,wimax`

Sadly none of it worked. Someone on Reddit helped me figure out that this is all probably due to the Android 12+ limitations and I remembered that I had a similar issue on my phone with Tasker and had to install Tasker Settings in order to solve it.
So my question is, would it be possible to somehow install Tasker Settings on my WearOS watch would that help me toggle the Bluetooth using the AutoWear app?
Thanks a lot!

**Comment by joaomgcd** [comment]
Unfortunately that's not possible because TaskerSettings can only "talk" to Tasker and not other apps, sorry! I would have to create a separate app for AutoWear itself and I'm not even sure it's possible on the watch (haven't tried it yet). Hope this clarifies it.
