### ISSUE TITLE
RedMagic 9 Pro Global Edition - Network Toggle - Bluetooth Fails - Wifi Works

### ISSUE THREAD

**Issue by FeintDoxx** [joaomgcd/TaskerSettings#46]
Red Magic 9 Pro
Android 14
REDMAGICOS9.0.13_NX769J_GB

Tasker 6.3.4-beta
TaskerSettings.Huawei.Xiaomi 1.7.1

So as title states on the RedMagic 9 Pro I cannot toggle bluetooth with TaskerSettings

Upon testing first of the two, TaskerSettings, creating a task: Bluetooth SET OFF; task will initiate but then hang indefinitely, play button stays and then has the pause button but setting the option to OFF, ON, or TOGGLE nothing occurs.
Same for wifi;

Tested the Huawei.Xiaomi version considering the brand of this phone and wifi toggle works with this version but bluetooth gives:

18.29.12/E exe: Turn Off Radios / Bluetooth [ Set: Off ]
18.29.12/LicenseCheckerTasker Checking cached only
18.29.12/LicenseCheckerTasker cache validity left -1355
18.29.12/LicenseCheckerTasker Cached status: Licensed
18.29.12/LicenseCheckerTasker Cached only: Licensed
18.29.12/Ew add wait type Bluetooth Status Group time 2147483647
18.29.12/Ew add wait type Bluetooth Status Group done
18.29.12/E add wait task
18.29.13/E Error: null
18.29.13/E Couldn't toggle bluetooth: : Tasker Settings doesn't have nearby or Bluetooth permissions?

Let me know if there's anything else I can do to help, I do NOT have the knowledge to tack this myself :|

As a side note, thank you for Tasker and all of the updates it has continued to receive, I remember first getting this for my Nexus 4!

**Comment by joaomgcd** [comment]
Did you try disabling and re-enabling the Nearby Devices and Bluetooth permission for the **Tasker Settings** app (not Tasker itself)?

Glad you still like Tasker after all that time! 😅

**Comment by FeintDoxx** [comment]
> Did you try disabling and re-enabling the Nearby Devices and Bluetooth permission for the **Tasker Settings** app (not Tasker itself)?
> 
> Glad you still like Tasker after all that time! 😅

That did the trick! I did have to force stop the application after making the changes to the permissions as attempting to toggle without FC and reopening resulted in the same as before where the task would run indefinitely without actually toggling.

I may have not used it a ton in recent years but have always found a reason to come back!

**Comment by FeintDoxx** [comment]
Basically had tested with your recommendation, got it to toggle wifi and bluetooth a couple times and then set my phone to the side as I had other things to complete. But when I went back to it after a couple of hours it would hang. Restarted the phone saw some of tasker settings got revoked with the TaskerSettings desktop app. Re-granted via the desktop app but just get the following.

17.45.36/E exe: Turn Off Radios / Bluetooth [
     Set: Off ]
17.45.36/LicenseCheckerTasker Checking cached only
17.45.36/LicenseCheckerTasker cache validity left -16481
17.45.36/LicenseCheckerTasker Cached status: Licensed
17.45.36/LicenseCheckerTasker Cached only: Licensed
17.45.36/Ew add wait type Bluetooth Status Group time 2147483647
17.45.36/Ew add wait type Bluetooth Status Group done
17.45.36/E add wait task
17.46.07/E Error: null
17.46.07/E Couldn't toggle bluetooth: : The source did not signal an event for 30 seconds and has been terminated.

17.48.14/E exe: Turn Off Radios / WiFi [
     Set: Toggle ]
17.48.14/LicenseCheckerTasker Checking cached only
17.48.14/LicenseCheckerTasker cache validity left -173655
17.48.14/LicenseCheckerTasker Cached status: Licensed
17.48.14/LicenseCheckerTasker Cached only: Licensed
17.48.14/M lastWifiDisableAgoMS: 1711493294058
17.48.14/E check AP state
17.48.14/Mirror android.net.ConnectivityManager.setMobileDataEnabled: unavailable
17.48.14/Mirror android.net.ConnectivityManager.setRadio: unavailable
17.48.14/Mirror android.net.wifi.WifiManager.setWifiApEnabled: unavailable
17.48.14/E AP state: 1
17.48.14/M lastWifiDisableAgoMS: 1711493294059
17.48.14/E current state: 1
17.48.14/E curval: 1
17.48.14/E WiFi: cur: false new: true
17.48.14/E WiFi: setWifiEnabled()
17.48.14/Ew add wait type Wifi Status Group time 2147483647
17.48.14/Ew add wait type Wifi Status Group done
17.48.14/M setKeepWifiOn: E/doWifiStatus1
17.48.14/E add wait task
17.48.44/E Error: null
17.48.44/E Couldn't toggle wifi: : The source did not signal an event for 30 seconds and has been terminated.

**Comment by FeintDoxx** [comment]
Was more diligent about the install procedure this time around, also realized Tasker Settings wasn't set to ignore red magics battery optimization only Tasker so pretty sure all good at this point. And this time around using TaskerSettings.1.7.1 non HuaweiXiaomi version; manually disabling/enabling Nearby Devices in settings manually got that going. Will continue messing around to see if it stops working but pretty sure that was the issue.

**Comment by joaomgcd** [comment]
Glad you got it! :)
