### ISSUE TITLE
HEUR:Trojan.AndroidOS.Boogr.gsh

### ISSUE THREAD

**Issue by bbk59** [joaomgcd/TaskerSettings#47]
When I'm trying to download TaskerSettings1.7.1.apk Kaspersky warns me that there is HEUR:Trojan.AndroidOS.Boogr.gsh inside.

**Comment by sp4rkie** [comment]
I think you have to ask Kaspersky  this question

**Comment by joaomgcd** [comment]
Unfortunately I can't control what Anti-virus apps report as viruses, sorry :( All I can say is that the app is open source and you can check the code to see exactly what it does. Sorry!
