### ISSUE TITLE
WiFi not turned on

### ISSUE THREAD

**Issue by BramvanSchagen** [joaomgcd/TaskerSettings#5]
Hi,

Connect To Wifi will only work if WiFi is turned on.

Can it not turn on Wifi as well ?

**Comment by joaomgcd** [comment]
You can use the **Wifi** action to do that.

**Comment by BramvanSchagen** [comment]
Hi,WiFi action Will not set WiFi to on without root access ...How to enable this without root access ?The new tasker-settings APK does not do this 😔Cheers BramOp 13 sep. 2021 14:10 schreef João Dias ***@***.***>:
You can use the Wifi action to do that.

**Comment by joaomgcd** [comment]
If you install this you don't need root access :) 

https://github.com/joaomgcd/TaskerSettings/releases/download/v1.3.0/TaskerSettings.apk

**Comment by BramvanSchagen** [comment]
Hi Joao,Tried it 😉Both tasker and tasker-settings are battery disabled.But still get this error (see pic).I use an OnePlus One with Lineage Os 18 (Android 11).Thanks in advance 👍Cheers BramOp 16 sep. 2021 16:26 schreef João Dias ***@***.***>:
If you install this you don't need root access :)
https://github.com/joaomgcd/TaskerSettings/releases/download/v1.3.0/TaskerSettings.apk

**Comment by joaomgcd** [comment]
Hi! Sorry, I didn't see a pic. Can you please attach it! Thank you!

**Comment by BramvanSchagen** [comment]
Hi, This one.Cheers BramOp 16 sep. 2021 19:25 schreef João Dias ***@***.***>:
Hi! Sorry, I didn't see a pic. Can you please attach it! Thank you!

**Comment by joaomgcd** [comment]
Hi. Sorry, still not seing the pic. :( Are you replying via email? Try replying in the Github website instead...

**Comment by BramvanSchagen** [comment]
![IMG_20210916_165547](https://user-images.githubusercontent.com/88943855/133756882-32e39794-1b8f-44d2-8915-07156315e018.jpg)

**Comment by BramvanSchagen** [comment]
Ok, this one 😃

**Comment by BramvanSchagen** [comment]
I also get a message that root rights are refused for Tasker (yes, the phone is rooted but I want to test it without root rights)

**Comment by BramvanSchagen** [comment]
Hi, does this clarify it a bit more ?

**Comment by joaomgcd** [comment]
Hi. Oh, if you have a rooted device, Tasker will only try to use that, sorry! That's why the error is happening :)

**Comment by BramvanSchagen** [comment]
Ok, thanks, tried it non-rooted and works perfect 👍

**Comment by joaomgcd** [comment]
👍
