### ISSUE TITLE
Tasker Settings not compatible with Samsung Galaxy Fold 6

### ISSUE THREAD

**Issue by plasticbiker** [joaomgcd/TaskerSettings#52]
Trying to install with Tasker Setting 1.7.1

![SmartSelect_20240731_182432_Package installer](https://github.com/user-attachments/assets/6564092b-25be-4b34-bec3-4e524161802e)

**Comment by joaomgcd** [comment]
Hi. Please check the note about Android 14 here: https://github.com/joaomgcd/TaskerSettings/

Sorry for the inconvenience!

**Comment by beer-matt** [comment]
@joaomgcd I think it would be useful if Tasker Permissions could include option to install Tasker Settings (including option to ignore version)?
I did raise [issue 31](https://github.com/joaomgcd/Tasker-Permissions/issues/31) for this..
