### ISSUE TITLE
popup when enabling WiFi

### ISSUE THREAD

**Issue by Abejo** [joaomgcd/TaskerSettings#53]
Hi, I'm trying to enable WiFi, it works ok, but a popup always appears to do so, the phone has HyperOS, I tried with several versions, but with all of them the popup appears. Is there a solution?

**Comment by joaomgcd** [comment]
Hi. If anything, that's a setting somewhere in your device's system settings that you have to change. Tasker itself doesn't show that popup. 
If you can find the system setting that disables that popup, it should work correctly! :)

Hope this helps!

**Comment by Abejo** [comment]
I tried installing the huawei/xiaomi version, but the popup appears anyway, I don't see a way to disable it, the phones I tested are Poco X5 Pro and Redmi Note 9S both with HyperOS 1.0.6.0 and 1.0.8.0 respectively
![photo_2024-09-25_09-57-20](https://github.com/user-attachments/assets/930e8027-56b3-4c3e-b5f0-cd0f2e65ace8)

**Comment by joaomgcd** [comment]
Unfortunately I don't have a way to disable those myself, sorry :( The best you can do is probably use AutoInput to try and click those automatically, but that requires the screen to be on at the time.
