### ISSUE TITLE
Unable to install on Samsung galaxy tab A9+

### ISSUE THREAD

**Issue by JJs-Code** [joaomgcd/TaskerSettings#54]
Upon attempting to install I get message "app not installed as app isn't compatible with your phone" I'm guessing that the app isn't compatible with all tablets, which is a shame, is there anything that can be done to fix this?

**Comment by joaomgcd** [comment]
Hi. Please check the note about Android 14 here: https://github.com/joaomgcd/TaskerSettings/

Sorry for the inconvenience!

**Comment by JJs-Code** [comment]
no probs i managed to get it installed using ADB and works fine now
