### ISSUE TITLE
Change wifi settings ask for extra confirmation MIUI 12

### ISSUE THREAD

**Issue by distante** [joaomgcd/TaskerSettings#6]
Hello, I tried the latest Tasker settings app and every time I run turn off/on task I get an extra toast to confirm it.

![Screenshot_2021-08-16-10-25-41-089_net dinglisch android taskerm](https://user-images.githubusercontent.com/5490201/129534232-ee3e1733-7c35-4f6e-92d3-43fd2a4a3c32.jpg)

Is there a way to prevent this?

**Comment by distante** [comment]
As update, I found this related thread but the workaround there (manually give the permission) does not work.

https://github.com/ThanosFisherman/WifiUtils/issues/38

**Comment by distante** [comment]
Oh ok, I gaved the permission to Tasker but not to Tasker Settings. Fixed

**Comment by MegaMatze** [comment]
Seems to not be working with MIUI 13. With all permissions set i still get the prompt

**Comment by joaomgcd** [comment]
Which prompt are you getting exactly?

**Comment by MegaMatze** [comment]
This one
![IMG_20220525_123445](https://user-images.githubusercontent.com/40768719/170243045-623bd8f9-3cc3-4bfe-bb6d-d505725a725d.jpg)

**Comment by joaomgcd** [comment]
That's a MIUI prompt and not something I can change. It's a system setting somewhere that you have to toggle. Sorry, not sure where, you'll need to find it
