### ISSUE TITLE
Getting this error in Tasker for the disable/enable camera action. It's related to Tasker settings.

### ISSUE THREAD

**Issue by Invisible3ck** [joaomgcd/TaskerSettings#7]
03.45.36/E add wait type EasyAction1 time 2147483647
03.45.36/E add wait type EasyAction1 done
03.45.36/E add wait task
03.45.41/E Error: 1
03.45.41/E java.util.concurrent.TimeoutException

**Comment by joaomgcd** [comment]
This usually means that Tasker can't communicate with the Tasker Settings app.

Did you make absolutely sure to follow all the steps for your specific device at https://dontkillmyapp.com/ for the Tasker Settings app (not Tasker itself)?

**Comment by Invisible3ck** [comment]
@joaomgcd Maybe Tasker is not compatible with Android 11? I open Tasker settings, it asks me for the location permission and I grant it and then it crashes. The same thing happens in Tasker when trying ot execute the camera task.

https://drive.google.com/file/d/1WiYxmL9eUTSUgd3IGVKJcXZh4el3na6e/view?usp=drivesdk

https://drive.google.com/file/d/1WRf3SlVX0jWi0oFdrnKq5g2mzSjvuWWB/view?usp=drivesdk

**Comment by joaomgcd** [comment]
You need to go to Android Settings and give the permission manually. This issue is described here: https://github.com/joaomgcd/TaskerSettings/releases/tag/v1.3.0
