### ISSUE TITLE
cannot pay for tasker

### ISSUE THREAD

**Issue by Zhaowei-Yu** [joaomgcd/TaskerSettings#8]
Hi there, I'm a Chinese user. Although I'd like to pay for tasker, but I can't due to some reason. So is there any other way to pay for it? Thanks!

**Comment by joaomgcd** [comment]
Hi there.
To purchase a license for the direct-purchase version please sign up as a Patron here: https://www.patreon.com/joaoapps
After you sign up I'll send the corresponding amount of licenses to you. :) Each $4 there grants you a license. 

If you want multiple licenses you can sign up with a higher tier right away (for example $8 for 2 licenses, $12 for 3 licenses, etc) or just wait the number of months until the correct $ amount has accumulated.

Let me know if you have any questions!

**Comment by Zhaowei-Yu** [comment]
> Hi there. To purchase a license for the direct-purchase version please sign up as a Patron here: https://www.patreon.com/joaoapps After you sign up I'll send the corresponding amount of licenses to you. :) Each $4 there grants you a license.
> 
> If you want multiple licenses you can sign up with a higher tier right away (for example $8 for 2 licenses, $12 for 3 licenses, etc) or just wait the number of months until the correct $ amount has accumulated.
> 
> Let me know if you have any questions!

Sorry to bother again. Does this mean I need to pay 4 USD every month?

**Comment by Kelvino9** [comment]
No, you don't have to continue the subscription for more than a month if you don't want to. The first month grants you one Tasker license already. You can immediately cancel the subscription afterwards.
