### ISSUE TITLE
"Wifi Connected" state problem with TaskerSettings

### ISSUE THREAD

**Issue by prestidigitonium** [joaomgcd/TaskerSettings#9]
Hello, I have Tasker 5.14.6 and TaskerSettings 1.2.0, I use android 11. All tasker needed permissions are allowed, I have root and I manually enabled TaskerSettings permissions (only sensors permission for 1.2.0) and I disabled battery optimizations for both apps. 
The problem is that when I create a profile using the "Wifi Connected" state, it's not triggered when I connect/disconnect from a network or when I turn off wifi. I tried with TaskerSettings 1.3.0 too (I manually allowed 1 more permission, so all permissions possible), but the problem is the same.

**Comment by joaomgcd** [comment]
Hi. Tasker Settings doesn't help with the **Wifi Connected** state, just with some Wifi actions.

Can you please export your profile's description (not xml) so I can take a look? Long-click the profile in Tasker->export description Thanks in advance

**Comment by prestidigitonium** [comment]
This is the profile exported:

Profilo: Wifi Collegato
    Impostazioni: Restore: no
    	Stato: WIFI collegato [ SSID:* MAC:* IP:* Attivo:Tutti ]
    
    
    
    Avvio Attività: Abilita Rotazione
    
    A1: Rotazione Automatica Schermo [
         Imposta: On ]
